apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pocdevops18
  labels:
    app: pocdevops18
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: pocdevops16-service
    spec:
      containers:
      - image: gcr.io/com-poc-ci-cd/myfirstjavaproject:1.0.18
        imagePullPolicy: IfNotPresent
        name: pocdevops16-service
        ports:
        - containerPort: 8080