apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pocdevops20
  labels:
    app: pocdevops20
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: pocdevops20-service
    spec:
      containers:
      - name: pocdevops20-service
        image: gcr.io/com-poc-ci-cd/myfirstjavaproject:1.0.20
        ports:
        - containerPort: 8080