apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pocdevops19
  labels:
    app: pocdevops19
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: pocdevops19-service
    spec:
      containers:
      - image: gcr.io/com-poc-ci-cd/myfirstjavaproject:1.0.19
#        imagePullPolicy: IfNotPresent
        name: pocdevops19-service
        ports:
        - containerPort: 8080