apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pocdevops
  labels:
    app: pocdevops
spec:
  replicas: 2
  template:
    metadata:
      labels:
        apps: pocdevops-service
    spec:
      containers:
      - name: pocdevops-service
        image: gcr.io/com-poc-ci-cd/pocdevops:1.0.11
        ports:
        - containerPort: 8080